version: '3'

services:
  chatgpt-demo:
    image: registry.aptero.co/aptero-chatgpt-demo:latest
    container_name: aptero-chatgpt-demo
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - OPENAI_API_KEY=YOUR_OPENAI_API_KEY
      # - HTTPS_PROXY=YOUR_HTTPS_PROXY
      # - OPENAI_API_BASE_URL=YOUR_OPENAI_API_BASE_URL
      # - HEAD_SCRIPTS=YOUR_HEAD_SCRIPTS
      # - PUBLIC_SECRET_KEY=YOUR_SECRET_KEY
      # - SITE_PASSWORD=YOUR_SITE_PASSWORD
      # - OPENAI_API_MODEL=YOUR_OPENAI_API_MODEL
    networks:
      webtraefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatgptdemo.rule=Host(`meet.aptero.co`) && PathPrefix(`/service/chatgpt`)"
      - "traefik.http.middlewares.chatgptdemo-stripprefix.stripprefix.prefixes=/service/chatgpt/"
      - "traefik.http.routers.chatgptdemo.middlewares=chatgptdemo-stripprefix@docker,https-redirectscheme@file"
      - "traefik.http.routers.chatgptdemo.entrypoints=websecure"
      - "traefik.http.routers.chatgptdemo.tls=true"

networks:
  webtraefik:
    external: true
